{
 "title": "Home Network",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">1</h1>"
   }
  },
  {
   "title": "Cable Modem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"192.168.100.1:80\",job=\"Cable Modem\",name=\"Cable Modem\"}\t"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">4</h1>"
   }
  },
  {
   "title": "Obihai VoIP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.18.5\",job=\"obihai\",name=\"Obihai VoIP\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">7</h1>"
   }
  },
  {
   "title": "Weather Station",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.18.107\",job=\"rpi-weatherstation\",name=\"Raspberry Pi Weather Station\"}"
    }
   ]
  },
  {
   "title": "Outbound Latency Test",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{instance=\"8.8.8.8\",job=\"Testing IP - 8.8.8.8\",name=\"Testing 8.8.8.8\",phase=\"rtt\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">2</h1>"
   }
  },
  {
   "title": "TP-Link Router",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.18.1\",job=\"TP-Link Router\",name=\"TP-Link Router\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 5 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">5</h1>"
   }
  },
  {
   "title": "UniFi AP - Basement",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"192.168.18.11:22\",job=\"unifi-basement\",name=\"Basement AP\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 5 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">8</h1>"
   }
  },
  {
   "title": "Outbound Test - 8.8.8.8",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"8.8.8.8\",job=\"Testing IP - 8.8.8.8\",name=\"Testing 8.8.8.8\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">3</h1>"
   }
  },
  {
   "title": "TP-Link Power Strip",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.18.2\",job=\"tplink-powerstrip\",name=\"TP-Link Kasa Power Strip\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 10 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">6</h1>"
   }
  },
  {
   "title": "UniFi AP - Back House",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"192.168.18.10:22\",job=\"unifi-backhouse\",name=\"Back House AP\"}\t"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 10 },
   "options": {
    "content": "<h1 style=\"font-size:10vw\">9</h1>"
   }
  },
  {
   "title": "Outbound Test - Google.com",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://google.com\",job=\"Testing DNS - Google.ca\"}"
    }
   ]
  }
 ]
}